### ISSUE TITLE
Add write topic to MqttItem

### ISSUE THREAD

**Issue by loewexy** [spacemanspiff2007/HABApp#190] opened 2020-12-23 14:22 UTC
Many MQTT Devices, like to ones created by zigbee2mqtt use one topic for the item state and another topic for changing the item state. It would be nice if we could create an MqttItem with both topics so that it can use the write topic for all writing operations and the other one only for read operations.

**Comment by spacemanspiff2007** [comment] 2020-12-23 15:58
How are they used together? I skipped over the documentation and it seems there are many ways it can be used (e.g. with json, with /state)

**Comment by loewexy** [comment] 2020-12-23 16:00
the simplest example would be that you read the brightness from zigbee2mqtt/my-bulb/brightness but you have to publish to zigbee2mqtt/my-bulb/set/brightness to change the Brightness.

**Comment by spacemanspiff2007** [comment] 2020-12-23 17:13
So it is always ``zigbee2mqtt/my-bulb/XXX`` and ``zigbee2mqtt/my-bulb/set/XXX``?

**Comment by loewexy** [comment] 2020-12-23 21:09
For zigbee2mqtt yes. If I remember correctly homegear uses `homegear/my-bulb/brightnes` and `homegear/set/my-bulb/brightnes` so the pattern is not easy to guess for different software. My idea would be to just have to parameters and set both of them.

**Comment by spacemanspiff2007** [comment] 2020-12-27 05:44
Do you just want the publish function to work on the different topic or do you think it's also interesting to keep the timestamps for the publishing item (last_change, last_update).
But if you want those you can always get them through the mqtt item for the publishing topic.
set_value and post_value should only work on the reading item, right?

**Comment by loewexy** [comment] 2020-12-27 11:33
Last change and Last update makes sense for the read channel. I did not know that set_value and post_value existed for the MqttItem and I cant find the documentation for that. But they seem to be writing to the item, therefore they should use the write topic, as this is dedicated for changing things. Writing to the read topic wont change anything at this point.

Personally I prefern MqttPairItem or MqttTwinItem since MqttReadWriteItem can lead to confusion because one may think that MqttItem is readonly if there is also a ReadWriteItem.

**Comment by spacemanspiff2007** [comment] 2020-12-28 05:44
I have added a MqttPairItem in the Dev branch. Would you be willing to try it out?

There is one issue left to tackle:
MqttItems get auto generated once a topic is received. When a topic is received before you create the MqttPairItem it will raise an error because it has the wrong type (MqttItem instead of MqttPairItem).
What do you think should happen? Should HABApp silently remove the MqttItem and replace it with a MqttPairItem?

**Comment by loewexy** [comment] 2020-12-28 16:12
Do you have an hint on how to install from the dev branch?

The automatic build for zigbee2mqtt is currently not documented. I guess it is used if None is supplied as write topic. If that is correct a little hint would be nice.

I am unsure about your open issue, since I do not fully understand how HABApp handles item creation. My understanding was that an Item is only created when the `get_item` method is called. But from your writing and the existence of `get_create_item` I guess I do not fully understand the mechanics here. Is this documented somewhere?

**Comment by spacemanspiff2007** [comment] 2020-12-28 18:02
> Do you have an hint on how to install from the dev branch?

If you use a venv just replace the contents of ``lib/site-packages/HABApp`` with the contents from ``HABApp`` from this repo and restart HABApp. You'll see that they contain the same files so it's just downloading the source and replacing the contents.

> I guess it is used if None is supplied as write topic. If that is correct a little hint would be nice.

If you look at the default it is None, so if you omit the argument it'll build automatically. I'll add a short sentence to the parameter description.

> I am unsure about your open issue, since I do not fully understand how HABApp handles item creation.

``get_item`` : return existing item
``get_create_item`` : return existing item or create item and return it

The issue is not with these functions but rather that HABApp currently automatically creates an ``MqttItem``if a message is received.
Then you create a rule and do ``get_create_item`` to create a MqttPairItem but there is already an existing ``MqttItem`` so you get an error. If you create the item before the message was received everything works.

**Comment by loewexy** [comment] 2020-12-29 12:16
I tried to use the new one, but I guess I ran into the conversion problem:
```
Error <class 'HABApp.mqtt.items.mqtt_item.MqttItem'> != <class 'HABApp.mqtt.items.mqtt_pair_item.MqttPairItem'> in process_msg:
File "/home/lukas/Desktop/habapp/lib/python3.8/site-packages/HABApp/core/wrapper.py", line 103, in f
    return func(*args, **kwargs)
File "/home/lukas/Desktop/habapp/lib/python3.8/site-packages/HABApp/mqtt/mqtt_connection.py", line 159, in process_msg
    127  def process_msg(self, client, userdata, message: mqtt.MQTTMessage):
 (...)
    155              log_msg._log(logging.DEBUG, f'{topic} ({message.qos}): {payload[:20]}...', [])
    156  
    157  
    158      # get the mqtt item
--> 159      _item = HABApp.mqtt.items.MqttItem.get_create_item(topic)
    160  
    ..................................................
     self = <HABApp.mqtt.mqtt_connection.MqttConnection object at 0x7feeec74f460>
     client = <paho.mqtt.client.Client object at 0x7feeec74f4c0>
     userdata = None
     message = <paho.mqtt.client.MQTTMessage object at 0x7feee8d06c10>
     mqtt.MQTTMessage = <class 'paho.mqtt.client.MQTTMessage'>
     log_msg._log = <method 'Logger._log' of <Logger HABApp.EventBus.mqtt (INFO)> __init__.py:1553>
     logging.DEBUG = 10
     HABApp.mqtt.items.MqttItem.get_create_item = <method 'MqttItem.get_create_item' of <class 'HABApp.mqtt.items.mqtt_item.MqttItem'> mqtt_item.py:12>
     topic = 'zigbee2mqtt/bulb-bett/brightness'
    ..................................................

```
The Rule I tested was:
```
import HABApp
from HABApp.mqtt.items import MqttPairItem
from datetime import timedelta

class Light(HABApp.Rule):
    def __init__(self):
        super().__init__()

        self.mqtt = MqttPairItem.get_create_item("zigbee2mqtt/bulb-bett/brightness")
        self.mqtt.publish("255")
        self.run_every(None, timedelta(seconds=4), self.test)

    def test(self):
        print("Hello" + str(self.mqtt.get_value()))
        if self.mqtt.get_value() < 100:
            self.mqtt.publish("255")
        else:
            self.mqtt.publish("1")

# Create Instances
Light()

```

> Since this is mainly all done by me it is sometimes really hard to write a good documentation. For me things are often clear and I don't see the problems so I don't remember to write it in the docs.

I see that. I guess a bit of general introduction on how HABapp works and interacts with Mqtt and Openhab would be nice. The concepts with Items only in HABapp or from both systems can be very confusing. Also I am not clear if the Openhab items are mainly Wrappers around rest calls or does HABapp have a copy from the complete state updated by openhabs event stream. But that are maybe things for another issue...

**Comment by spacemanspiff2007** [comment] 2020-12-29 12:35
> I tried to use the new one, but I guess I ran into the conversion problem:

That's another issue I just fixed in the dev branch. Could you try again?

You can write the rule like this, the ``get_value()`` is just if you want to add a default that is used in case the value is None
```python
import HABApp
from HABApp.mqtt.items import MqttPairItem
from datetime import timedelta

class Light(HABApp.Rule):
    def __init__(self):
        super().__init__()

        self.mqtt = MqttPairItem.get_create_item("zigbee2mqtt/bulb-bett/brightness")
        self.mqtt.publish("255")
        self.run_every(None, timedelta(seconds=4), self.test)

    def test(self):
        print("Hello" + str(self.mqtt.value))  # <----
        if self.mqtt < 100:  # <----
            self.mqtt.publish("255")
        else:
            self.mqtt.publish("1")

# Create Instances
Light()
```

**Comment by loewexy** [comment] 2020-12-29 12:47
Okay now it works with publish(). If I use set_value or post_value() it does not work. But that is the point where I could need some explanation on the general idea what each function is for. The all seem to be equivalent for me.

**Comment by spacemanspiff2007** [comment] 2020-12-29 15:04
``set_value`` and ``post_value`` change the value of the item on the HABApp side (they work local only).
``publish`` and the oh-functions trigger something outside of HABApp.

**Comment by spacemanspiff2007** [comment] 2020-12-29 15:43
I've made a new release which includes the changes.
If you have any more ideas or questions you can open another issue or write something in the openhab community.
Looking forward to hearing from you.

**Closed by spacemanspiff2007** 2020-12-29 15:43 UTC

**Comment by loewexy** [comment] 2020-12-29 15:46
Thanks for the quick update. The problem with converting MqttItems to MqttPairItems is also fixed now?

I think most of my Ideas would be on improving the documentation. The software works very nicely.

**Comment by spacemanspiff2007** [comment] 2020-12-29 15:48
> Thanks for the quick update. The problem with converting MqttItems to MqttPairItems is also fixed now?

This is rather a braking change and something for 0.19.0.
I'll create a follow up issue.

**Comment by loewexy** [comment] 2020-12-29 15:51
So currently there must not be a message in the MQTT topic before the creation process is executed? What if we have a retained message which comes up on every start?

**Comment by spacemanspiff2007** [comment] 2020-12-29 16:05
Typically that shouldn't be the read/write topic of your devices but rather e.g. a configuration topic of homie.
The timespan is typically short for other messages (a couple of secs) so I don't think this is too critical.
If you ever experience an exception (but be aware what the root cause is) you can delete the existing item with
```HABApp.core.Items.pop_item('my_topic')```.
If you are unsure you can open an issue and I'll gladly help you out.

**Comment by loewexy** [comment] 2020-12-29 16:29
Okay that seems to be an edgecase, we will see if I ever encounter it.
