### ISSUE TITLE
Suggestion: More methods for countdown timers

### ISSUE THREAD

**Issue by sarain** [spacemanspiff2007/HABApp#265] opened 2022-01-29 11:11 UTC
I'm just starting out with HABApp and love the freedom it offers.  I am finding a few places where I could use some additional capabilities to cleanly accomplish what I'm trying to do though.

Two things in particular that I would find useful are new methods to stop and to query the state of countdown timer objects.
There are times in my rules where I don't want to let a countdown callback run if certain conditions change after it was started.

The reset() method works for restarting/resetting the timer but, once it's started, there doesn't seem to be a clean way to just stop it.
I dug into the code a little bit and see that the countdown timer relies on an AsyncScheduler class from eascheduler.  That class includes a remove_job() method that looks like it might be useful to accomplish this.

Also, there are times where it would be nice to know if I already started a countdown timer.  For this, maybe checking if self._parent.jobs is empty from within a new method in the CountdownJob class?

These feel like generally useful features for the countdown timer and I know I would have uses for them.  Are these features you would consider adding?  Or are there already ways to accomplish these things that I've missed?

**Comment by NickWaterton** [comment] 2022-01-29 17:11
I also use the countdown timer. I've had some trouble with it, as if you try to cancel a timer that is already cancelled, it throws an exception instead of silently failing.

This is more of a problem than you would think in async code, so in my class subclassing countdown timer, it's a bit of a torturous try/except mess.

You also can't restart a cancelled timer, you have to recreate it (which is different from an expired or running timer). This makes for an inconsistent interface, if you want a persistent timer that you can cancel or restart at will. Like for controlling lights based on motion sensors.

I didn't want to patch the base class, so I made my own subclass, but in reality I think the design of the countdown timer class is flawed.

Ideally, it shouldn't throw exceptions for none problematic calls, and you should be able to restart cancelled timers (assuming that you haven't destroyed the object).

Just my thoughts on the subject.

**Comment by spacemanspiff2007** [comment] 2022-01-30 04:50
> I've had some trouble with it, as if you try to cancel a timer that is already cancelled, it throws an exception instead of silently failing.

Maybe this is a naming confusion, Cancel destroys the timer and does not stop the countdown.
That's why you can't start a canceled scheduler.
At some point the link between the scheduler and the jobs has to be removed, otherwise it'll stay in memory forever.
That's the reason I chose to implement an exception because it's a good indication that the code using it is buggy because why would you try to cancel an object that has been already removed from the scheduler.

Maybe if there would be a ``stop`` call it'll be more clear but I have to take a look at the implementation again,

**Comment by NickWaterton** [comment] 2022-01-30 05:41
> Maybe this is a naming confusion, Cancel destroys the timer and does not stop the countdown.

Maybe it is a naming confusion. Perhaps the problem is that there is no way of stopping a running timer without destroying it, there is no easy way of telling if a timer has ended, and the destroy method is named cancel.

The reason for cancelling a timer that has already been cancelled is that there is no easy way of telling if a timer has expired or been cancelled (and you can't stop it any other way), so it's not "buggy code", it's a problem with the implementation of the timer.

Useful properties would be:

* is_running
* is_stopped (convenience property)
* time_remaining (in seconds)

Useful methods

* Start()
* Reset()
* Countdown(seconds)
* Cancel()
* Destroy()

Calling Cancel() on a timer that is already cancelled should not throw an exception, it just stops the timer and sets the time_remaining to 0.

**Comment by sarain** [comment] 2022-01-30 10:05
To avoid conflicts or backwards compatibility issues with the existing cancel() method, a method named stop() would probably be a safer choice for stopping a countdown timer.  I agree cancel() is a bit of of a confusing name for what it currently does though.
As mentioned above, the remove_job() method in AsyncScheduler looks like it might be useful to accomplish this.

**Comment by spacemanspiff2007** [comment] 2022-01-31 11:50
``cancel()`` removes all the other scheduled jobs, too. So I think it would be good to keep the interface aligned here.

Currently I think ``stop()`` would be the most appropriate. 
``Start()`` is misleading, since a call does also reset the timer thus the name ``reset()``

``time_remaining`` could be just ``remaining`` (not sure about that yet).
Should it return secs or a ``timedelta``?

**Comment by NickWaterton** [comment] 2022-02-01 00:09
> time_remaining could be just remaining (not sure about that yet).
Should it return secs or a timedelta?

I was thinking seconds, as it would be something you could send to a Number item (if you want to display it). I don't think it's something you would need accurate to milliseconds.

**Comment by sarain** [comment] 2022-02-01 03:46
For what it's worth, I would vote for it to return a timedelta, since that preserves the most information about the remaining time.  If you just want seconds, it's easy enough to just call .total_seconds() on it.

**Comment by spacemanspiff2007** [comment] 2022-02-01 08:19
> I don't think it's something you would need accurate to milliseconds.

If it'll be seconds then it'll be the difference in seconds with sub second accuracy.

> What would happen to an expired timer? Can you restart it (ie reset()), or does it become orphaned? Or garbage collected - ie would you have to recreate it first before resetting?

It'll be the same as now. A call to ``reset()`` will restart the timer. You don't have to recreate the timer if it is expired.

> One of the problems I had with the countdown timer was that it was not atomic, so timing was a continual issue

That's really strange. Accessing the scheduler is actually thread safe so there should be no issues what so ever.

**Comment by NickWaterton** [comment] 2022-02-01 22:09
> That's really strange. Accessing the scheduler is actually thread safe so there should be no issues what so ever.

I though it was strange as well. My first version of the createTimer() class set the timer instance to None when it was cancelled(). Then if you attempted to reset() it, and it was None, it recreated the timer, and then reset() it.

This didn't work reliably, it seemed that recreating the timer took some time (or at least several steps), so if two different rules called reset() on the same timer at almost the same time, one may or may not throw an exception, depending on how closely together they were called.

I concluded that the individual steps of creating a countdown timer may be atomic, but the process as a whole was not. That's why I went with the try .. except version, as that was reliable.

**Comment by spacemanspiff2007** [comment] 2022-02-14 06:13
I've added a implementation to the eascheduler. You guys can try it out by manually updating the version.
I went for the timedelta but it works for every job not only the countdown job.

**Comment by sarain** [comment] 2022-02-16 07:08
Cool!  Thanks!  I'll check this out as soon as I get a chance.

**Comment by sarain** [comment] 2022-02-16 07:18
Super minor thing, but the change log date(s) for this in the eascheduler readme say 2021 instead of 2022 :)

**Comment by spacemanspiff2007** [comment] 2022-02-17 09:08
Maybe because the feature has been long overdue? 😉 
I've not yet implemented the convenience function because they make no sense for the other jobs since they are always running or not. Depending on the feedback I might think about adding it to the countdown.

**Comment by spacemanspiff2007** [comment] 2022-07-29 11:11
I'll close this since imho everything is implemented. If you are still missing something feel free to reopen

**Closed by spacemanspiff2007** 2022-07-29 11:11 UTC
