### ISSUE TITLE
Add support for new ALIVE event

### ISSUE THREAD

**Issue by RichieRogers** [spacemanspiff2007/HABApp#293] opened 2022-06-18 19:33 UTC
Hi,
Also posted this on the OpenHab forum, but hoping someone here can also help.
Since updating to the latest OpenHab version (3.3.0 Build #2953 - also #2952) any events in OpenHab now generate the following errors in the HabApp log file and (obviously) no longer work:
[2022-06-18 20:20:39,662] [                   HABApp]    ERROR | Error 'topic' in on_sse_event:
[2022-06-18 20:20:39,663] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection_handler/sse_handler.py", line 25, in on_sse_event
[2022-06-18 20:20:39,664] [                   HABApp]    ERROR |     22   def on_sse_event(event_dict: dict):
[2022-06-18 20:20:39,664] [                   HABApp]    ERROR |     23       try:
[2022-06-18 20:20:39,665] [                   HABApp]    ERROR |     24           # Lookup corresponding OpenHAB event
[2022-06-18 20:20:39,666] [                   HABApp]    ERROR | --> 25           event = get_event(event_dict)
[2022-06-18 20:20:39,667] [                   HABApp]    ERROR |     26
[2022-06-18 20:20:39,668] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:20:39,669] [                   HABApp]    ERROR |      event_dict = {'type': 'ALIVE'}
[2022-06-18 20:20:39,669] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:20:39,670] [                   HABApp]    ERROR |
[2022-06-18 20:20:39,671] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/map_events.py", line 29, in get_event
[2022-06-18 20:20:39,671] [                   HABApp]    ERROR |     27   def get_event(_in_dict: dict) -> OpenhabEvent:
[2022-06-18 20:20:39,672] [                   HABApp]    ERROR |     28       event_type: str = _in_dict['type']
[2022-06-18 20:20:39,672] [                   HABApp]    ERROR | --> 29       topic: str = _in_dict['topic']
[2022-06-18 20:20:39,673] [                   HABApp]    ERROR |     30
[2022-06-18 20:20:39,673] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:20:39,674] [                   HABApp]    ERROR |      _in_dict = {'type': 'ALIVE'}
[2022-06-18 20:20:39,674] [                   HABApp]    ERROR |      OpenhabEvent = <class 'HABApp.openhab.events.base_event.OpenhabEvent'>
[2022-06-18 20:20:39,675] [                   HABApp]    ERROR |      event_type = 'ALIVE'
[2022-06-18 20:20:39,675] [                   HABApp]    ERROR |     ..................................................

I'm running on Raspberry Pi 4 with the latest Raspian OS (Bullseye) and have changed nothing else - just run the usual apt update and apt upgrade commands.

Is anyone else having a similar issue or can advise on a fix?

Thanks,
Richie

**Comment by RichieRogers** [comment] 2022-06-18 19:50
Just doing some basic debugging and part of this issue is that the on_sse_event doesn't always seem to have "topic" in it:
[2022-06-18 20:46:39,441] [HABApp.openhab.connection]  WARNING | RR_TEST: {'type': 'ALIVE'}
[2022-06-18 20:46:39,666] [                   HABApp]    ERROR | Error 'topic' in on_sse_event:
[2022-06-18 20:46:39,666] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection_handler/sse_handler.py", line 26, in on_sse_event
[2022-06-18 20:46:39,666] [                   HABApp]    ERROR |     22   def on_sse_event(event_dict: dict):
[2022-06-18 20:46:39,667] [                   HABApp]    ERROR |     23       try:
[2022-06-18 20:46:39,667] [                   HABApp]    ERROR |     24           # Lookup corresponding OpenHAB event
[2022-06-18 20:46:39,667] [                   HABApp]    ERROR |     25           log_warning(log, f'RR_TEST: {event_dict}')
[2022-06-18 20:46:39,667] [                   HABApp]    ERROR | --> 26           event = get_event(event_dict)
[2022-06-18 20:46:39,668] [                   HABApp]    ERROR |     27
[2022-06-18 20:46:39,668] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:46:39,668] [                   HABApp]    ERROR |      event_dict = {'type': 'ALIVE'}
[2022-06-18 20:46:39,668] [                   HABApp]    ERROR |      log = <Logger HABApp.openhab.connection (INFO)>
[2022-06-18 20:46:39,669] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:46:39,669] [                   HABApp]    ERROR |
[2022-06-18 20:46:39,670] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/map_events.py", line 29, in get_event
[2022-06-18 20:46:39,670] [                   HABApp]    ERROR |     27   def get_event(_in_dict: dict) -> OpenhabEvent:
[2022-06-18 20:46:39,671] [                   HABApp]    ERROR |     28       event_type: str = _in_dict['type']
[2022-06-18 20:46:39,671] [                   HABApp]    ERROR | --> 29       topic: str = _in_dict['topic']
[2022-06-18 20:46:39,671] [                   HABApp]    ERROR |     30
[2022-06-18 20:46:39,671] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:46:39,672] [                   HABApp]    ERROR |      _in_dict = {'type': 'ALIVE'}
[2022-06-18 20:46:39,672] [                   HABApp]    ERROR |      OpenhabEvent = <class 'HABApp.openhab.events.base_event.OpenhabEvent'>
[2022-06-18 20:46:39,672] [                   HABApp]    ERROR |      event_type = 'ALIVE'
[2022-06-18 20:46:39,672] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 20:46:39,673] [                   HABApp]    ERROR |
[2022-06-18 20:46:39,673] [                   HABApp]    ERROR | KeyError: 'topic'

Could something in OpenHab have changed recently?

Thanks, 
Richie

**Comment by RichieRogers** [comment] 2022-06-18 20:22
Ok, so further investigation seems to indicate this (in map_events.py) no longer works correctly:
def get_event(_in_dict: dict) -> OpenhabEvent:
    event_type: str = _in_dict['type']
    topic: str = _in_dict['topic']

So an "event_type" still gets treated as a topic (I think).
My limited Python knowledge is stuck on any further testing/solution :(

Thanks,
Richie

**Comment by RichieRogers** [comment] 2022-06-18 21:09
Even more investigation an "debugging (floundering):
[2022-06-18 22:06:39,506] [                   HABApp]    ERROR | Error Unknown Event: ALIVE for {'type': 'ALIVE'} in on_sse_event:
[2022-06-18 22:06:39,507] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/map_events.py", line 52, in get_event
[2022-06-18 22:06:39,507] [                   HABApp]    ERROR |     30   def get_event(_in_dict: dict):
[2022-06-18 22:06:39,508] [                   HABApp]    ERROR |  (...)
[2022-06-18 22:06:39,509] [                   HABApp]    ERROR |     48
[2022-06-18 22:06:39,509] [                   HABApp]    ERROR |     49
[2022-06-18 22:06:39,510] [                   HABApp]    ERROR |     50       # Find event from implemented events
[2022-06-18 22:06:39,510] [                   HABApp]    ERROR |     51       try:
[2022-06-18 22:06:39,510] [                   HABApp]    ERROR | --> 52           return __event_lookup[event_type].from_dict(topic, payload)
[2022-06-18 22:06:39,511] [                   HABApp]    ERROR |     53       except KeyError:
[2022-06-18 22:06:39,511] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,511] [                   HABApp]    ERROR |      _in_dict = {'type': 'ALIVE'}
[2022-06-18 22:06:39,512] [                   HABApp]    ERROR |      __event_lookup = {'ItemStateEvent': <class 'HABApp.openhab.events.item_events.ItemStateEvent'>,
[2022-06-18 22:06:39,512] [                   HABApp]    ERROR |                        'ItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.ItemStateChangedEvent'>,
[2022-06-18 22:06:39,512] [                   HABApp]    ERROR |                        'ItemCommandEvent': <class 'HABApp.openhab.events.item_events.ItemCommandEvent'>,
[2022-06-18 22:06:39,513] [                   HABApp]    ERROR |                        'ItemAddedEvent': <class 'HABApp.openhab.events.item_events.ItemAddedEvent'>,
[2022-06-18 22:06:39,513] [                   HABApp]    ERROR |                        'ItemUpdatedEvent': <class 'HABApp.openhab.events.item_events.ItemUpdatedEvent'>,
[2022-06-18 22:06:39,513] [                   HABApp]    ERROR |                        'ItemRemovedEvent': <class 'HABApp.openhab.events.item_events.ItemRemovedEvent'>,
[2022-06-18 22:06:39,513] [                   HABApp]    ERROR |                        'ItemStatePredictedEvent': <class 'HABApp.openhab.events.item_events.ItemStatePredictedEvent'>,
[2022-06-18 22:06:39,514] [                   HABApp]    ERROR |                        'GroupItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.GroupItemStateChangedEvent'>,
[2022-06-18 22:06:39,514] [                   HABApp]    ERROR |                        'ChannelTriggeredEvent': <class 'HABApp.openhab.events.channel_events.ChannelTriggeredEvent'>,
[2022-06-18 22:06:39,514] [                   HABApp]    ERROR |                        'ThingStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingStatusInfoEvent'>,
[2022-06-18 22:06:39,515] [                   HABApp]    ERROR |                        'ThingStatusInfoChangedEv...: <class 'HABApp.openhab.events.thing_events.ThingStatusInfoChangedEvent'>,
[2022-06-18 22:06:39,515] [                   HABApp]    ERROR |                        'ThingFirmwareStatusInfoE...: <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>,
[2022-06-18 22:06:39,515] [                   HABApp]    ERROR |                        'ConfigStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingConfigStatusInfoEvent'>,
[2022-06-18 22:06:39,515] [                   HABApp]    ERROR |                        'FirmwareStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>}
[2022-06-18 22:06:39,516] [                   HABApp]    ERROR |      event_type = 'ALIVE'
[2022-06-18 22:06:39,516] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,516] [                   HABApp]    ERROR |
[2022-06-18 22:06:39,517] [                   HABApp]    ERROR | KeyError: 'ALIVE'
[2022-06-18 22:06:39,517] [                   HABApp]    ERROR |
[2022-06-18 22:06:39,517] [                   HABApp]    ERROR | While handling the above exception, another exception occurred:
[2022-06-18 22:06:39,517] [                   HABApp]    ERROR |
[2022-06-18 22:06:39,518] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection_handler/sse_handler.py", line 25, in on_sse_event
[2022-06-18 22:06:39,518] [                   HABApp]    ERROR |     22   def on_sse_event(event_dict: dict):
[2022-06-18 22:06:39,518] [                   HABApp]    ERROR |     23       try:
[2022-06-18 22:06:39,519] [                   HABApp]    ERROR |     24           # Lookup corresponding OpenHAB event
[2022-06-18 22:06:39,519] [                   HABApp]    ERROR | --> 25           event = get_event(event_dict)
[2022-06-18 22:06:39,519] [                   HABApp]    ERROR |     26
[2022-06-18 22:06:39,520] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,520] [                   HABApp]    ERROR |      event_dict = {'type': 'ALIVE'}
[2022-06-18 22:06:39,520] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,521] [                   HABApp]    ERROR |
[2022-06-18 22:06:39,521] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/map_events.py", line 54, in get_event
[2022-06-18 22:06:39,521] [                   HABApp]    ERROR |     30   def get_event(_in_dict: dict):
[2022-06-18 22:06:39,522] [                   HABApp]    ERROR |  (...)
[2022-06-18 22:06:39,522] [                   HABApp]    ERROR |     50       # Find event from implemented events
[2022-06-18 22:06:39,522] [                   HABApp]    ERROR |     51       try:
[2022-06-18 22:06:39,523] [                   HABApp]    ERROR |     52           return __event_lookup[event_type].from_dict(topic, payload)
[2022-06-18 22:06:39,523] [                   HABApp]    ERROR |     53       except KeyError:
[2022-06-18 22:06:39,523] [                   HABApp]    ERROR | --> 54           raise ValueError(f'Unknown Event: {event_type:s} for {_in_dict}')
[2022-06-18 22:06:39,524] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,524] [                   HABApp]    ERROR |      _in_dict = {'type': 'ALIVE'}
[2022-06-18 22:06:39,524] [                   HABApp]    ERROR |      __event_lookup = {'ItemStateEvent': <class 'HABApp.openhab.events.item_events.ItemStateEvent'>,
[2022-06-18 22:06:39,525] [                   HABApp]    ERROR |                        'ItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.ItemStateChangedEvent'>,
[2022-06-18 22:06:39,525] [                   HABApp]    ERROR |                        'ItemCommandEvent': <class 'HABApp.openhab.events.item_events.ItemCommandEvent'>,
[2022-06-18 22:06:39,525] [                   HABApp]    ERROR |                        'ItemAddedEvent': <class 'HABApp.openhab.events.item_events.ItemAddedEvent'>,
[2022-06-18 22:06:39,525] [                   HABApp]    ERROR |                        'ItemUpdatedEvent': <class 'HABApp.openhab.events.item_events.ItemUpdatedEvent'>,
[2022-06-18 22:06:39,526] [                   HABApp]    ERROR |                        'ItemRemovedEvent': <class 'HABApp.openhab.events.item_events.ItemRemovedEvent'>,
[2022-06-18 22:06:39,526] [                   HABApp]    ERROR |                        'ItemStatePredictedEvent': <class 'HABApp.openhab.events.item_events.ItemStatePredictedEvent'>,
[2022-06-18 22:06:39,526] [                   HABApp]    ERROR |                        'GroupItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.GroupItemStateChangedEvent'>,
[2022-06-18 22:06:39,527] [                   HABApp]    ERROR |                        'ChannelTriggeredEvent': <class 'HABApp.openhab.events.channel_events.ChannelTriggeredEvent'>,
[2022-06-18 22:06:39,527] [                   HABApp]    ERROR |                        'ThingStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingStatusInfoEvent'>,
[2022-06-18 22:06:39,527] [                   HABApp]    ERROR |                        'ThingStatusInfoChangedEv...: <class 'HABApp.openhab.events.thing_events.ThingStatusInfoChangedEvent'>,
[2022-06-18 22:06:39,527] [                   HABApp]    ERROR |                        'ThingFirmwareStatusInfoE...: <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>,
[2022-06-18 22:06:39,528] [                   HABApp]    ERROR |                        'ConfigStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingConfigStatusInfoEvent'>,
[2022-06-18 22:06:39,528] [                   HABApp]    ERROR |                        'FirmwareStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>}
[2022-06-18 22:06:39,528] [                   HABApp]    ERROR |      event_type = 'ALIVE'
[2022-06-18 22:06:39,529] [                   HABApp]    ERROR |     ..................................................
[2022-06-18 22:06:39,529] [                   HABApp]    ERROR |
[2022-06-18 22:06:39,530] [                   HABApp]    ERROR | ValueError: Unknown Event: ALIVE for {'type': 'ALIVE'}

Could there be a new 'ALIVE' event being implemented by OpenHab that HabApp can't handle?

Thanks,
Richie

**Comment by spacemanspiff2007** [comment] 2022-06-27 03:43
Root cause is https://github.com/openhab/openhab-core/pull/2983.
Will be fixed in the next couple of weeks.

**Closed** 2022-07-07 08:02 UTC
